# Generated by Django 4.0 on 2021-12-15 22:08

from __future__ import unicode_literals
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=100)),
                ('no_of_pages', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
    ]
