# Generated by Django 4.0 on 2021-12-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_newssource_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsSource',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
