# Generated by Django 4.0 on 2021-12-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_newssource_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nsource',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.newssource'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.topic'),
        ),
    ]
