# Generated by Django 4.0 on 2021-12-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_nsource_article_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='nsource',
            new_name='newsSource',
        ),
    ]
