# Generated by Django 4.0 on 2021-12-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('refer_to_friend', models.BooleanField()),
                ('rating', models.CharField(choices=[('One Star', 'One Star'), ('Two Stars', 'Two Stars'), ('Three Stars', 'Three Stars'), ('Four Stars', 'Four Stars'), ('Five Stars', 'Five Stars')], max_length=15)),
                ('article_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('about', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=1000)),
                ('article_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='AuthNote',
            fields=[
                ('auth_note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('article_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
