# Generated by Django 4.0 on 2021-12-17 11:10

import attributes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthNote',
            fields=[
                ('article_id', models.PositiveSmallIntegerField()),
                ('auth_note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('user_id', models.PositiveSmallIntegerField()),
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('refer_to_friend', models.BooleanField()),
                ('rating', models.CharField(choices=[(attributes.models.RatingChoice['UN'], 'One Star'), (attributes.models.RatingChoice['DE'], 'Two Stars'), (attributes.models.RatingChoice['TR'], 'Three Stars'), (attributes.models.RatingChoice['CA'], 'Four Stars'), (attributes.models.RatingChoice['CI'], 'Five Stars')], max_length=15)),
                ('article_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
