# Generated by Django 4.0 on 2021-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('One Star', 'One Star'), ('Two Stars', 'Two Stars'), ('Three Stars', 'Three Stars'), ('Four Stars', 'Four Stars'), ('Five Stars', 'Five Stars')], max_length=15),
        ),
    ]
